import type { MorphemeKind, RootListItem } from './roots.types';

type RootOriginKey = 'latin' | 'greek' | 'old_english' | 'french' | 'other';

const ORIGIN_LABELS: Record<RootOriginKey, string> = {
  latin: '拉丁语源',
  greek: '希腊语源',
  old_english: '古英语语源',
  french: '法语语源',
  other: '综合语源',
};

const ADVANCED_ROWS = [
  'root|acer|latin|尖、酸、敏锐|acute、acrid、acerbic|11',
  'root|acou|greek|听|acoustic、acoustics|7',
  'root|ambul|latin|行走|ambulance、ambulate、preamble|8',
  'root|amat|latin|爱|amateur、amiable、amorous|9',
  'root|anthrop|greek|人类|anthropology、misanthrope|10',
  'root|aqu|latin|水|aquatic、aquarium、aqueduct|12',
  'root|arch|greek|统治、起源|monarch、anarchy、archetype|13',
  'root|astro|greek|星体|astronomy、astronaut、astrology|12',
  'root|bar|greek|重量、压力|barometer、baryon、baritone|6',
  'root|bath|greek|深度|bathysphere、bathos|5',
  'root|bell|latin|战争|rebellion、belligerent|8',
  'root|brev|latin|短|brief、abbreviate、brevity|12',
  'root|cad|latin|落下|cadence、decay、cascade|10',
  'root|calor|latin|热|calorie、calorific|7',
  'root|carn|latin|肉|carnivore、carnival、incarnate|10',
  'root|celer|latin|快|accelerate、celerity|8',
  'root|centr|greek|中心|central、concentric、eccentric|14',
  'root|cept|latin|拿、取|accept、concept、intercept|18',
  'root|cise|latin|切|concise、precise、incision|12',
  'root|clin|greek|倾斜|incline、decline、clinical|11',
  'root|corp|latin|身体|corporate、corpse、incorporate|16',
  'root|cosm|greek|宇宙、秩序|cosmos、cosmetic、cosmopolitan|12',
  'root|crat|greek|统治、力量|democrat、autocrat、bureaucracy|10',
  'root|cresc|latin|生长|crescent、increase、decrease|12',
  'root|culp|latin|责备、罪|culprit、culpable|6',
  'root|derm|greek|皮肤|dermatology、epidermis|9',
  'root|dextr|latin|右、灵巧|dexterity、ambidextrous|6',
  'root|dign|latin|值得、尊严|dignity、dignify、indignant|10',
  'root|domin|latin|主人、统治|dominant、domain、dominate|13',
  'root|dorm|latin|睡眠|dormitory、dormant|7',
  'root|dox|greek|观点、信念|orthodox、paradox|8',
  'root|drom|greek|跑、道路|hippodrome、syndrome|6',
  'root|dur|latin|硬、持久|during、durable、endure|14',
  'root|dynam|greek|力量|dynamic、dynamite|9',
  'root|err|latin|游荡、错误|error、erratic、errant|10',
  'root|fort|latin|强壮、运气|fortify、effort、fortune|13',
  'root|fract|latin|破碎|fraction、fracture、fragile|15',
  'root|fug|latin|逃跑|refuge、fugitive、centrifugal|10',
  'root|fus|latin|倒、熔合|confuse、infuse、fusion|16',
  'root|gnos|greek|知道|diagnosis、prognosis、agnostic|10',
  'root|gyn|greek|女性|gynecology、misogyny|7',
  'root|heli|greek|太阳|helium、heliocentric|7',
  'root|hem|greek|血|hemoglobin、hemisphere、anemia|9',
  'root|herb|latin|草、植物|herbivore、herbal|6',
  'root|hetero|greek|不同|heterogeneous、heterodox|8',
  'root|hydr|greek|水|hydrate、hydraulic、hydrogen|14',
  'root|hypn|greek|睡眠|hypnosis、hypnotic|6',
  'root|iso|greek|相等|isolate、isotope、isometric|8',
  'root|liber|latin|自由、书|liberty、liberal、library|13',
  'root|lith|greek|石头|lithograph、megalith|6',
  'root|loc|latin|地方|local、allocate、relocate|15',
  'root|luc|latin|光|lucid、translucent、illustrate|12',
  'root|magn|latin|大|magnify、magnificent、magnitude|14',
  'root|mal|latin|坏、恶|malfunction、malice、malnutrition|13',
  'root|mater|latin|母亲、材料|maternal、material、matrix|12',
  'root|medi|latin|中间|medium、mediate、medieval|15',
  'root|morph|greek|形态|morphology、metamorphosis|10',
  'root|naut|greek|船、航行|nautical、astronaut|7',
  'root|nov|latin|新|novel、innovate、renovate|14',
  'root|numer|latin|数字|number、enumerate、numerous|13',
  'root|omni|latin|全部|omnibus、omnivore、omnipotent|8',
  'root|pac|latin|和平|peace、pacify、pact|12',
  'root|pater|latin|父亲|paternal、patriot、patriarch|9',
  'root|pel|latin|推、驱动|compel、repel、propel|15',
  'root|pend|latin|悬挂、称量|depend、suspend、pending|16',
  'root|phil|greek|爱|philosophy、philanthropy、bibliophile|12',
  'root|phob|greek|恐惧|phobia、claustrophobia|9',
  'root|plac|latin|取悦、平静|please、placid、complacent|10',
  'root|polis|greek|城市|metropolis、politics|9',
  'root|pon|latin|放置|position、compose、exponent|18',
  'root|prim|latin|第一|primary、prime、primitive|12',
  'root|punct|latin|点、刺|punctual、puncture、punctuate|11',
  'root|quer|latin|寻找、询问|query、quest、inquire|14',
  'root|rect|latin|直、正确|correct、direct、rectangle|16',
  'root|reg|latin|统治、规则|regular、regime、regulate|17',
  'root|rupt|latin|断裂|interrupt、rupture、bankrupt|15',
  'root|san|latin|健康|sanitary、sane、sanitize|10',
  'root|sci|latin|知道|science、conscious、omniscient|16',
  'root|sequ|latin|跟随|sequence、consequence、subsequent|17',
  'root|solv|latin|松开、解决|solve、dissolve、resolve|15',
  'root|soph|greek|智慧|philosophy、sophisticated|8',
  'root|tang|latin|触摸|tangible、contact、contagion|12',
  'root|tempor|latin|时间|temporary、contemporary|14',
  'root|therm|greek|热|thermal、thermometer|10',
  'root|tox|greek|毒|toxic、intoxicate、toxin|9',
  'root|urb|latin|城市|urban、suburb、urbane|9',
  'root|vac|latin|空|vacuum、vacant、vacation|12',
  'root|ven|latin|来|convene、intervene、adventure|18',
  'root|ver|latin|真实|verify、verdict、verisimilar|13',
  'root|vers|latin|转|reverse、convert、diverse|18',
  'root|vit|latin|生命|vital、vitamin、revive|13',
  'root|viv|latin|活|vivid、survive、vivacious|12',
  'prefix|ante-|latin|在前|antecedent、antedate|7',
  'prefix|bene-|latin|好、善|benefit、benevolent|9',
  'prefix|eu-|greek|好、正常|eulogy、euphoria|7',
  'prefix|extra-|latin|超出、在外|extraordinary、extracurricular|11',
  'prefix|fore-|old_english|预先、前面|forecast、foresee|12',
  'prefix|hemi-|greek|半|hemisphere、hemicycle|6',
  'prefix|hypo-|greek|在下、不足|hypothesis、hypoglycemia|8',
  'prefix|intra-|latin|在内|intravenous、intranet|7',
  'prefix|meta-|greek|之后、变化、超越|metaphor、metabolism|10',
  'prefix|multi-|latin|多|multilingual、multitude|14',
  'prefix|neo-|greek|新|neoclassical、neonatal|7',
  'prefix|ob-|latin|朝向、阻挡|object、obstacle、obvious|13',
  'prefix|out-|old_english|超过、向外|outperform、outlook|12',
  'prefix|para-|greek|旁边、类似、异常|parallel、paradox、parasite|13',
  'prefix|peri-|greek|周围|perimeter、periscope|7',
  'prefix|poly-|greek|多|polygon、polyglot|10',
  'prefix|pseudo-|greek|假的|pseudonym、pseudoscience|6',
  'prefix|retro-|latin|向后、回溯|retrospect、retroactive|7',
  'prefix|semi-|latin|半|semiconductor、semifinal|11',
  'prefix|syn-|greek|共同、同时|synthesis、synchronize|13',
  'prefix|ultra-|latin|超越、极端|ultraviolet、ultramodern|9',
  'prefix|under-|old_english|在下、不足|underestimate、undergo|14',
  'suffix|-acy|latin|性质、状态|accuracy、privacy|8',
  'suffix|-age|french|行为、集合、费用|storage、coverage|11',
  'suffix|-algia|greek|疼痛|neuralgia、nostalgia|6',
  'suffix|-ant|latin|人、物、性质|assistant、dominant|13',
  'suffix|-arium|latin|场所、容器|aquarium、planetarium|6',
  'suffix|-cule|latin|小|molecule、minuscule|7',
  'suffix|-ee|french|接受动作的人|employee、trainee|8',
  'suffix|-ence|latin|状态、性质|difference、existence|15',
  'suffix|-esque|french|……风格的|picturesque、Kafkaesque|5',
  'suffix|-ette|french|小、女性化|kitchenette、cigarette|6',
  'suffix|-gen|greek|产生者|oxygen、pathogen|8',
  'suffix|-graphy|greek|书写、记录学科|geography、biography|9',
  'suffix|-ian|latin|属于……的人|historian、musician|13',
  'suffix|-ile|latin|能……的、倾向|fragile、juvenile|8',
  'suffix|-itis|greek|炎症|arthritis、bronchitis|7',
  'suffix|-let|french|小|booklet、leaflet|7',
  'suffix|-meter|greek|测量仪|thermometer、barometer|8',
  'suffix|-oid|greek|像……的|humanoid、asteroid|7',
  'suffix|-phile|greek|爱好者|bibliophile、anglophile|6',
  'suffix|-phobia|greek|恐惧|claustrophobia、xenophobia|7',
  'suffix|-scope|greek|观察仪器|telescope、microscope|9',
  'suffix|-some|old_english|具有……特征|troublesome、lonesome|7',
  'suffix|-tude|latin|状态、性质|attitude、magnitude|8',
  'combining_form|cardio|greek|心脏|cardiology、cardiogram|8',
  'combining_form|cephalo|greek|头|cephalopod、encephalitis|6',
  'combining_form|cranio|greek|颅骨|craniology、cranial|5',
  'combining_form|crypto|greek|隐藏|cryptography、cryptic|8',
  'combining_form|eco|greek|家、环境|ecology、economy|10',
  'combining_form|gastro|greek|胃|gastronomy、gastroenterology|8',
  'combining_form|neuro|greek|神经|neurology、neuron|9',
  'combining_form|osteo|greek|骨|osteology、osteoporosis|7',
  'combining_form|psycho|greek|心灵|psychology、psychoanalysis|10',
  'combining_form|rhino|greek|鼻|rhinoceros、rhinitis|6',
  'combining_form|somato|greek|身体|somatic、psychosomatic|6',
  'combining_form|theo|greek|神|theology、atheist|7',
  'combining_form|zoo|greek|动物|zoology、zootopia|7',
];

function parseAdvancedRow(row: string, index: number): RootListItem {
  const [kind, form, origin, meaning, examples, count] = row.split('|');
  const originKey = origin as RootOriginKey;
  const kindKey = kind as MorphemeKind;
  return {
    id: `advanced-${kindKey}-${form.replace(/[^a-z]/gi, '') || index}`,
    kind: kindKey,
    form,
    origin: originKey,
    originLabel: ORIGIN_LABELS[originKey],
    meaning,
    extendedMeaning: `进阶词源层词素，常见于 ${examples}。`,
    level: 'advanced',
    derivativeCount: Number(count) || 0,
  };
}

export const ADVANCED_MORPHEME_CATALOG: RootListItem[] = ADVANCED_ROWS.map(parseAdvancedRow);
