import { ADVANCED_MORPHEME_CATALOG } from './advanced-morpheme-catalog';
import type { MorphemeKind, RootListItem } from './roots.types';

type RootOriginKey = 'latin' | 'greek' | 'old_english' | 'french' | 'other';

const RAW_MORPHEMES = [
  'root|act|latin|拉丁语 agere|做、行动|active、action、react 都围绕行动展开。|18',
  'root|anim|latin|拉丁语 anima|生命、精神|animal、animate、unanimous 中表示生命力或心意。|12',
  'root|ann|latin|拉丁语 annus|年|annual、anniversary 表示年度或周年。|10',
  'root|aud|latin|拉丁语 audire|听|audio、audience、auditorium 都与听有关。|13',
  'root|bio|greek|希腊语 bios|生命|biology、biography、biotech 的生命语义核心。|15',
  'root|cap|latin|拉丁语 capere|抓、取、拿|capture、capacity、concept 中有抓取或容纳的含义。|20',
  'root|ced|latin|拉丁语 cedere|走、让步|precede、proceed、concede 表示行进或让出。|17',
  'root|chron|greek|希腊语 chronos|时间|chronology、synchronize 都围绕时间顺序。|9',
  'root|cid|latin|拉丁语 caedere|切、杀|decide 是切断选择，homicide 是杀人。|11',
  'root|civ|latin|拉丁语 civis|市民、城市|civil、civic、civilization 的社会组织含义。|10',
  'root|clud|latin|拉丁语 claudere|关闭|include、exclude、conclude 都有封闭边界感。|16',
  'root|cogn|latin|拉丁语 cognoscere|知道、认识|recognize、cognition 表示认知和识别。|12',
  'root|cred|latin|拉丁语 credere|相信|credit、credible、creed 都与信任相关。|13',
  'root|cur|latin|拉丁语 currere|跑、流动|current、occur、course 表示流动或发生。|18',
  'root|cycl|greek|希腊语 kyklos|圆、循环|cycle、recycle、encyclopedia 中表示环形或循环。|9',
  'root|dem|greek|希腊语 demos|人民|democracy、demographic 与人群和公众有关。|8',
  'root|dict|latin|拉丁语 dicere|说、讲|dictionary、predict、contradict 都来自言说语义。|15',
  'root|duc|latin|拉丁语 ducere|引导、带领|produce、conduct、educate 都有带出或引导含义。|20',
  'root|fac|latin|拉丁语 facere|做、制造|factory、factor、effect 表示制作或造成。|22',
  'root|fer|latin|拉丁语 ferre|带来、承载|transfer、refer、prefer 都有带向某处的感觉。|18',
  'root|fin|latin|拉丁语 finis|边界、结束|final、define、infinite 都与界限有关。|14',
  'root|flu|latin|拉丁语 fluere|流动|fluent、influence、fluid 表示流动和影响。|11',
  'root|form|latin|拉丁语 forma|形状、形式|inform、transform、formal 都围绕形式变化。|24',
  'root|gen|greek|希腊语 genos|出生、产生、种类|generate、genetic、gender 表示产生或类别。|21',
  'root|geo|greek|希腊语 ge|地球、土地|geography、geology、geometry 中表示大地。|10',
  'root|grad|latin|拉丁语 gradus|步、等级|graduate、gradual、upgrade 表示台阶或递进。|14',
  'root|graph|greek|希腊语 graphein|写、画|photograph、graphic、paragraph 都有书写或图像含义。|18',
  'root|ject|latin|拉丁语 jacere|投掷|project、reject、objective 都有投向之意。|17',
  'root|jur|latin|拉丁语 jus|法律、誓言|jury、justice、injury 的法理语义来源。|9',
  'root|lect|latin|拉丁语 legere|读、选择|select、collect、lecture 表示选择或读取。|17',
  'root|log|greek|希腊语 logos|言语、学科、逻辑|logic、biology、dialogue 中表示话语或学科。|25',
  'root|man|latin|拉丁语 manus|手|manual、manage、manufacture 与手工和操控相关。|16',
  'root|mem|latin|拉丁语 memoria|记忆|memory、memorial、remember 都围绕记忆。|12',
  'root|mit|latin|拉丁语 mittere|送、派|submit、transmit、mission 表示送出或派遣。|22',
  'root|mob|latin|拉丁语 movere|移动|mobile、motion、remove 都是移动语义。|19',
  'root|mort|latin|拉丁语 mors|死亡|mortal、immortal、mortality 表示死亡或有限生命。|8',
  'root|path|greek|希腊语 pathos|感受、疾病|empathy、pathology 表示感受或病理。|12',
  'root|ped|latin|拉丁语 pes|脚|pedal、pedestrian、expedition 与脚和行走相关。|10',
  'root|phon|greek|希腊语 phone|声音|phone、symphony、phonetic 表示声音。|11',
  'root|photo|greek|希腊语 phos|光|photo、photosynthesis、photograph 与光有关。|13',
  'root|port|latin|拉丁语 portare|携带、运输|transport、export、support 都有承载或携带含义。|18',
  'root|scrib|latin|拉丁语 scribere|写|describe、inscription、script 都表示书写。|16',
  'root|spec|latin|拉丁语 specere|看|inspect、respect、spectacle 表示观察或看待。|20',
  'root|spir|latin|拉丁语 spirare|呼吸|inspire、spirit、respire 与呼吸和精神相关。|12',
  'root|struct|latin|拉丁语 struere|建造、堆积|structure、construct、destructive 的核心是建造或破坏结构。|20',
  'root|tele|greek|希腊语 tele|远|telephone、television、telescope 表示远距离。|12',
  'root|ten|latin|拉丁语 tenere|握住、保持|contain、retain、tenant 表示持有或保持。|17',
  'root|tract|latin|拉丁语 trahere|拉、拖|attract、contract、abstract 都带有拉取或牵引。|18',
  'root|vid|latin|拉丁语 videre|看见|video、evidence、provide 与看见或呈现有关。|16',
  'root|voc|latin|拉丁语 vocare|叫、声音|voice、vocabulary、advocate 都来自发声或呼叫。|18',
  'root|volv|latin|拉丁语 volvere|卷、转|evolve、revolve、volume 表示卷动或展开。|12',
  'prefix|a-|greek|希腊/拉丁前缀|无、非、向|asymmetry、atypical 中表示否定。|10',
  'prefix|ab-|latin|拉丁前缀|离开、偏离|abnormal、absent、abstract 表示离开原位。|12',
  'prefix|ad-|latin|拉丁前缀|朝向、接近|adapt、advance、adhere 表示向某处靠近。|18',
  'prefix|anti-|greek|希腊前缀|反对、抵抗|antibody、antiwar、antithesis 表示对抗。|16',
  'prefix|auto-|greek|希腊前缀|自己、自动|automatic、autobiography 表示自我或自动。|14',
  'prefix|bi-|latin|拉丁前缀|二、双|bilingual、bicycle、binary 表示两个。|12',
  'prefix|circum-|latin|拉丁前缀|环绕、周围|circumstance、circumference 表示围绕。|8',
  'prefix|co-|latin|拉丁前缀|共同、一起|cooperate、coworker、coexist 表示共同。|20',
  'prefix|contra-|latin|拉丁前缀|相反、反对|contradict、contrast 表示方向相反。|9',
  'prefix|de-|latin|拉丁前缀|向下、去除、否定|decrease、decode、devalue 表示下降或去掉。|22',
  'prefix|dis-|latin|拉丁前缀|分开、否定|disagree、disconnect、display 表示分离或否定。|24',
  'prefix|en-|french|法语/拉丁前缀|使成为、进入|enable、encourage、enlarge 表示使其进入某状态。|14',
  'prefix|ex-|latin|拉丁前缀|向外、前任|export、exit、exclude 表示向外。|19',
  'prefix|hyper-|greek|希腊前缀|过度、超越|hyperactive、hypersensitive 表示过度。|8',
  'prefix|in-|latin|拉丁前缀|进入、否定|inject 表示进入；invisible 表示否定。|26',
  'prefix|inter-|latin|拉丁前缀|在……之间、互相|international、interact 表示相互或之间。|18',
  'prefix|micro-|greek|希腊前缀|小、微|microscope、microchip 表示微小。|11',
  'prefix|mis-|old_english|古英语前缀|错误、坏|misunderstand、mislead 表示错误方向。|10',
  'prefix|non-|latin|拉丁前缀|不、非|nonprofit、nonviolent 表示否定。|16',
  'prefix|post-|latin|拉丁前缀|之后|postwar、postpone 表示之后。|9',
  'prefix|pre-|latin|拉丁前缀|预先、在前|predict、preview、prepare 表示提前。|20',
  'prefix|pro-|latin|拉丁前缀|向前、支持|progress、promote 表示向前或支持。|22',
  'prefix|re-|latin|拉丁前缀|再、回|rewrite、return、rebuild 表示再次或返回。|28',
  'prefix|sub-|latin|拉丁前缀|在下、次级|subway、submarine、subtitle 表示下方或从属。|16',
  'prefix|super-|latin|拉丁前缀|在上、超越|supermarket、superhuman 表示超过或在上。|13',
  'prefix|trans-|latin|拉丁前缀|跨越、转移|transport、translate、transform 表示穿越或转变。|18',
  'prefix|un-|old_english|古英语前缀|不、相反动作|unknown、undo 表示否定或撤销。|30',
  'suffix|-able|latin|拉丁后缀|可……的|readable、valuable 表示可被完成或具有能力。|18',
  'suffix|-al|latin|拉丁后缀|……的、名词化|natural、arrival 表示性质或结果。|20',
  'suffix|-ance|french|法语后缀|状态、行为|importance、performance 表示状态或行为结果。|14',
  'suffix|-ary|latin|拉丁后缀|与……有关的、场所|dictionary、library 表示相关物或场所。|9',
  'suffix|-ate|latin|拉丁后缀|使成为、动词后缀|activate、educate 表示使其进入某状态。|17',
  'suffix|-dom|old_english|古英语后缀|领域、状态|freedom、kingdom 表示状态或领域。|7',
  'suffix|-er|old_english|古英语后缀|人、物、比较级|teacher、worker、higher 表示执行者或比较。|24',
  'suffix|-ful|old_english|古英语后缀|充满……的|helpful、careful 表示充满某性质。|12',
  'suffix|-hood|old_english|古英语后缀|身份、时期|childhood、neighborhood 表示身份阶段或群体。|7',
  'suffix|-ic|greek|希腊后缀|……的|historic、economic 表示相关性质。|18',
  'suffix|-ify|latin|拉丁后缀|使……化|simplify、classify 表示使成为某状态。|12',
  'suffix|-ion|latin|拉丁后缀|行为、结果|action、construction 表示动作或结果。|30',
  'suffix|-ish|old_english|古英语后缀|有点……的、类似|childish、greenish 表示类似或略带。|8',
  'suffix|-ism|greek|希腊后缀|主义、体系|capitalism、realism 表示思想体系。|10',
  'suffix|-ist|greek|希腊后缀|从事者、主义者|artist、scientist 表示人。|12',
  'suffix|-ity|latin|拉丁后缀|性质、状态|ability、quality 表示抽象性质。|20',
  'suffix|-ive|latin|拉丁后缀|有……倾向的|active、creative 表示性质或倾向。|18',
  'suffix|-ize|greek|希腊后缀|使……化|modernize、realize 表示使成为某状态。|14',
  'suffix|-less|old_english|古英语后缀|无……的|hopeless、careless 表示缺少。|12',
  'suffix|-logy|greek|希腊后缀|学科、研究|biology、psychology 表示学科。|11',
  'suffix|-ment|french|法语后缀|行为、结果、状态|development、movement 表示动作结果。|22',
  'suffix|-ness|old_english|古英语后缀|性质、状态|happiness、darkness 表示抽象状态。|16',
  'suffix|-or|latin|拉丁后缀|人、物|actor、collector 表示执行者。|15',
  'suffix|-ous|latin|拉丁后缀|充满……的|dangerous、famous 表示性质充满。|13',
  'suffix|-ship|old_english|古英语后缀|身份、关系|friendship、leadership 表示关系或身份。|8',
  'suffix|-tion|latin|拉丁后缀|行为、结果|education、relation 表示动作或结果。|28',
];

function parseMorpheme(row: string, index: number): RootListItem {
  const [kind, form, origin, originLabel, meaning, extendedMeaning, count] = row.split('|');
  return {
    id: `catalog-${kind}-${form.replace(/[^a-z]/gi, '') || index}`,
    kind: kind as MorphemeKind,
    form,
    origin: origin as RootOriginKey,
    originLabel,
    meaning,
    extendedMeaning,
    level: 'core',
    derivativeCount: Number(count) || 0,
  };
}

export const MORPHEME_CATALOG: RootListItem[] = RAW_MORPHEMES.map(parseMorpheme).concat(
  ADVANCED_MORPHEME_CATALOG,
);
